name: build kitty
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/kitty.yaml

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
    bundle:
        name: Bundle test (${{ matrix.os }})
        runs-on: ${{ matrix.os }}
        container:
            image: ubuntu:20.04
        strategy:
            matrix:
                os: [ubuntu-latest]
        env:
            KITTY_BUNDLE: 1
            KITTY_SANITIZE: 1
        steps:
          - name: Checkout source code
            uses: actions/checkout@v7.0.1
            with:
              fetch-depth: 10
              persist-credentials: false
        
          - name: Inject Git for Checkout Action
            env:
              DEBIAN_FRONTEND: noninteractive
            run: |
              apt-get update && apt-get install -y git wget curl build-essential \
                  software-properties-common unzip libssl-dev zlib1g-dev \
                  libbz2-dev libreadline-dev libsqlite3-dev llvm \
                  libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev \
                  libffi-dev liblzma-dev
          
          - name: clone kitty
            uses: sudosubin/git-clone-action@v1.0.1
            with: 
              repository: kovidgoyal/kitty
              ref: master
              path: kitty

          - name: Install Go
            uses: actions/setup-go@v7.0.0
            with:
              go-version-file: ./kitty/go.mod

          # - name: 设置 Python 环境
          #   env:
          #     DEBIAN_FRONTEND: noninteractive
          #   run: |
          #     add-apt-repository ppa:deadsnakes/ppa -y
          #     apt update
          #     apt install python3.12 python3.12-venv python3.12-dev -y
          
          - name: Install python version
            uses: gabrielfalcao/pyenv-action@v18
            id: pyenv_setup
            with:
              default: 3.12
              command: |
                pip install -U pip  # upgrade pip after installing python
                cd ./kitty
                python3 .github/workflows/ci.py build

          - name: Build kitty
            working-directory: ./kitty
            run: |
              PYENV_ROOT="${{ steps.pyenv_setup.outputs.pyenv_root }}"
              export PATH="$PYENV_ROOT/bin:$PYENV_ROOT/shims:$PATH"
              echo "set pyenv"
              eval "$(pyenv init -)"
              echo "list env versions"
              pyenv install 3.12 -s
              pyenv versions
              echo "set version"
              pyenv global 3.12
              python3 --version
              python3 .github/workflows/ci.py build

          - name: Test kitty
            working-directory: ./kitty
            run: |
              pyenv global 3.12
              python3 --version
              python3 .github/workflows/ci.py test

    linux-dev:
        name: Test ./dev.sh and benchmark
        runs-on: ubuntu-latest
        container:
            image: ubuntu:20.04
        steps:
          - name: Checkout source code
            uses: actions/checkout@v7.0.1
            with:
              fetch-depth: 10
              persist-credentials: false

          - name: Inject Git for Checkout Action
            env:
              DEBIAN_FRONTEND: noninteractive
            run: |
              apt-get update && apt-get install -y git wget curl build-essential \
                  software-properties-common unzip libssl-dev zlib1g-dev \
                  libbz2-dev libreadline-dev libsqlite3-dev llvm \
                  libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev \
                  libffi-dev liblzma-dev
          
          - name: clone kitty
            uses: sudosubin/git-clone-action@v1.0.1
            with: 
              repository: kovidgoyal/kitty
              ref: master
              path: kitty

          - name: Install build deps
            env:
              DEBIAN_FRONTEND: noninteractive
            run: |
              add-apt-repository ppa:deadsnakes/ppa -y
              apt-get update
              apt-get install -y curl xz-utils build-essential git pkg-config libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libgl1-mesa-dev libxkbcommon-x11-dev libfontconfig-dev libx11-xcb-dev libdbus-1-dev
              echo apt install python3.12 python3.12-venv python3.12-dev -y

          - name: Install python version
            uses: gabrielfalcao/pyenv-action@v18
            with:
              default: 3.12
              command: pip install -U pip  # upgrade pip after installing python


          - name: Install Go
            uses: actions/setup-go@v7.0.0
            with:
              go-version-file: ./kitty/go.mod

          - name: Build kitty
            working-directory: ./kitty
            run: |
              pyenv global 3.12
              python3 --version
              ./dev.sh build

          - name: Run benchmarks
            working-directory: ./kitty
            run: |
              pyenv global 3.12
              python3 --version
              ./benchmark.py
