# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: build weektodo for arm64

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-22.04-arm

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: clone weektodo rep
      uses: sudosubin/git-clone-action@v1.0.1
      with: 
        repository: manuelernestog/weektodo
        ref: main
        path: weektodo
    - run: 'sed -i ''s/target: \["deb", "rpm", "pacman","AppImage"],/target: ["deb"],/'' vue.config.js'
      working-directory: ./weektodo
      shell: bash
    - name: Install Linux Dependencies
      run: |
          sudo apt-get update
          sudo apt-get install wine libwine
          sudo apt-get install snapd
          sudo apt-get install libarchive-tools libopenjp2-tools
          sudo apt-get install ruby-full build-essential
          sudo snap install snapcraft --classic
          sudo gem install fpm
    - run: | 
        export USE_SYSTEM_FPM=true
        npm install --global yarn
        yarn install
        yarn run electron:build
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      working-directory: ./weektodo            
    - name: Github Release
      uses: softprops/action-gh-release@v2.2.1
      with:
        files: 
        - ./weektodo/dist_electron/WeekToDo-2.2.0-arm64.AppImage
        - ./weektodo/dist_electron/WeekToDo-2.2.0-arm64.deb
        name: WeekToDo-2.2.0-arm64.AppImage
        tag_name: weektodo-2.2
        prerelease: true
        token: ${{ secrets.GITHUB_TOKEN }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
    
